# Available ruby versions: http://rubies.travis-ci.org/

language: ruby
sudo: false

os:
  - linux
  - osx

rvm:
  - 2.3.8 # support ends March 2019
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-9.2.0.0
  - jruby-head

cache: bundler

script:
  - bundle exec rake test
  - bundle exec rake rubocop

branches:
  except:
    - "readme-edits"

before_install:
  - gem update --system
  # bundler installation needed for jruby-head
  # https://github.com/travis-ci/travis-ci/issues/5861
  - gem install bundler

# Travis OS X support is pretty janky. These are some hacks to include tests
# only on versions that actually work.
# (last tested: 2016-11)
matrix:
  # exclude: {}
  # include: {}

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

  # return results as soon as mandatory versions are done
  fast_finish: true
